config/routes.rb
Rails.application.routes.draw do
  resources :votes, only: [:create, :destroy]
  resources :discussions do
    resources :comments
  end
  resources :courses do
    resources :lessons do
      member do
        put :complete
      end
    end
  end
  resources :enrollments, only: [:create, :destroy]

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => 'registrations'}
  resources :users

  root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/discussion.rb
class Discussion < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  has_many :votes, through: :comments
  belongs_to :user

  validates_presence_of :title, :content
end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  before_action :set_discussion, only: [:show, :edit, :update, :destroy]

  # GET /discussions
  # GET /discussions.json
  def index
    @discussions = Discussion.all.order("created_at DESC")
    @discussion = Discussion.new
    respond_to do |format|
      format.html { render :index}
      format.json { render json: @discussions}
    end
  end

  # GET /discussions/1
  # GET /discussions/1.json
  def show
    @count = Discussion.all.count
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @discussion }
    end
  end

  # GET /discussions/new
  def new
    @discussion = current_user.discussions.build
  end

  # GET /discussions/1/edit
  def edit
  end

  # POST /discussions
  # POST /discussions.json
  def create
    @discussion = current_user.discussions.build(discussion_params)
    if @discussion.save
      render json: @discussion, status: 201
    else
      render :new
    end
  end

  # PATCH/PUT /discussions/1
  # PATCH/PUT /discussions/1.json
  def update
    respond_to do |format|
      if @discussion.update(discussion_params)
        format.html { redirect_to @discussion, notice: 'Discussion was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /discussions/1
  # DELETE /discussions/1.json
  def destroy
    @discussion.destroy
    respond_to do |format|
      format.html { redirect_to discussions_url, notice: 'Discussion was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_discussion
      @discussion = Discussion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def discussion_params
      params.require(:discussion).permit(:title, :content)
    end
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
end

app/views/discussions/_form.html.erb
  <%= form_for(@discussion) do |f| %>
    <% if @discussion.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@discussion.errors.count, "error") %> prohibited this discussion from being saved:</h2>

        <ul>
        <% @discussion.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <fieldset class="form-group">
      <%= f.label :title %><br>
      <%= f.text_field :title, class: "form-control" %>
    </fieldset>

    <fieldset class="form-group">
      <%= f.label :content %><br>
      <%= f.text_area :content, class: "form-control" %>
    </fieldset>
    <div class="actions">
      <%= f.submit 'Submit', class: "btn btn-primary" %>
    </div>
  <% end %>

app/views/discussions/edit.html.erb
<div class="container bg-white">
<h1>Editing Discussion</h1>

<%= render 'form' %>

<%= link_to 'Show', @discussion %> |
<%= link_to 'Back', discussions_path %>
</div>

app/views/discussions/index.html.erb
<div class="container">
<h1>Listing Discussions | <%= link_to 'New Discussion', new_discussion_path %></h1>
</div>

<div class="j-discussion">
</div>

<!-- begin form -->
<div class="container">
  <div class="row">
    <div class="col-md-8 bg-white" style="margin-top: 10px;">
      <h3> New Discussion </h3>
<%= form_for(@discussion) do |f| %>
  <% if @discussion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@discussion.errors.count, "error") %> prohibited this discussion from being saved:</h2>

      <ul>
      <% @discussion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control", required: true %>
  </fieldset>

  <fieldset class="form-group">
    <%= f.label :content %><br>
    <%= f.text_area :content, class: "form-control", required: true %>
  </fieldset>
  <div class="actions">
    <%= f.submit 'Submit', class: "btn btn-primary pull-right" %>
  </div>
<% end %>
</div>
</div>
</div>


<script type="text/javascript" charset="utf-8">
$(function () {
  $('.show-btn').on('click', function(e){
    event.stopPropagation();
    console.log("clicked");
  });

  $('form').submit(function(event) {
    event.preventDefault();
    event.stopPropagation();
    var values = $(this).serialize();
    var posting = $.post('discussions', values);

    posting.done(function(data){
        var html = "";
        var newDiscussion = new DiscussionData(data["id"], data["title"], data["content"], data["user"], data["comments"]);
        html += '<div class="discussion-thread" data-id=' + newDiscussion.id + '>';
        html += '<div class="container">';
        html += '  <div class="row" style="margin-top: 10px;">';
        html += '    <div class="col-md-8 bg-white">';
        html += '      <div class="media">';
        html += '        <div class="media-left">';
        html += '            <%= image_tag("pen") %>';
        html += '        </div>';
        html += '        <div class="media-body">';
        html += '          <h3 class="media-heading font-1">' + newDiscussion.title + '</h3>';
        html += '          <p>Asked by ' + newDiscussion.author() + '</p>';
        html += '          <a href="/discussions/' + newDiscussion.id + '">Show</a>';
        html += '       </div>';
        html += '      </div>';
        html += '    </div>';
        html += '  </div>';
        html += '</div>';
        html += '</div>';

      $(".j-discussion").append(html);
      console.log(html)
    });
  });

  function DiscussionData(id, title, content, user, comments){
    this.id = id;
    this.title = title;
    this.content = content;
    this.user = user;
    this.comments = comments;
    this.author = function(){
      return user["name"];
    }
  }

  $(document).ready(function() {
    var html = "";
    $.get("/discussions.json", function(data) {
         var len = data.length;

         for(var i = 0; i < len; i++){
          var newDiscussion = new DiscussionData(data[i]["id"], data[i]["title"], data[i]["content"], data[i]["user"], data[i]["comments"])
          html += '<div class="discussion-thread" data-id=' + newDiscussion.id + '>'
          html += '<div class="container">'
          html += '  <div class="row" style="margin-top: 10px;">'
          html += '    <div class="col-md-8 bg-white">'
          html += '      <div class="media">'
          html += '        <div class="media-left">'
          html += '            <%= image_tag("pen") %>'
          html += '        </div>'
          html += '        <div class="media-body">'
          html += '          <h3 class="media-heading font-1">' + newDiscussion.title + '</h3>'
          html += '          <p>Asked by ' + newDiscussion.author() + '</p>'
          html += '          <a href="/discussions/' + newDiscussion.id + '">Show</a>'
          html += '       </div>'
          html += '      </div>'
          html += '    </div>'
          html += '  </div>'
          html += '</div>'
          html += '</div>'
         }
      $(".j-discussion").html(html);
    });
  });
});


</script>

app/views/discussions/new.html.erb
<div class="container bg-white">
  <h1>New Discussion</h1>

  <%= render 'form' %>

  <%= link_to 'Back', discussions_path %>
</div>

app/views/discussions/show.html.erb
<div class="container discussion-show" data-id="<%=@discussion.id%>" data-count="<%= @count %>">
  <div class="row" style="padding-bottom: 10px;">
   <div class="col-md-9 bg-white">
      <h2 class="font-2 title"><%= @discussion.title %></h2>
      <hr>
      <h4 class='font-3 content'><%= @discussion.content %></h4>
      <br>
      <p class='author'>Posted by <%= @discussion.user.email %> <%= time_ago_in_words(@discussion.created_at) %> ago</p>

      <div class="links btn-group">
        <button class="next-js btn btn-primary">Next Discussion</button>
        <%= link_to "Back", discussions_path, class: "btn btn-default" %>
        <% if @discussion.user_id == current_user.id || current_user.admin? %>
          <a href="2/edit" class="btn btn-default edit">Edit</a>
          <a data-confirm="Are you sure?" class="btn btn-default delete" rel="nofollow" data-method="delete" href="2">Delete</a>
        <% end %>
      </div>
      <h3>Reply to question:</h3>
      <!-- renders the comments form -->
      <%= render 'comments/form' %>
     </div>
    </div>
    <hr>
    <div class="comments">
      <%= render @discussion.comments.order_by_vote %>
    </div>
</div>

<!-- renders the _comment.html.erb partial file. -->
<script>
$(function(){
  $(".next-js").click(function(){
    var id = $(".discussion-show").data("id");
    var last = $(".discussion-show").data("count");
    var next = id == last ? 1 : id + 1;
    var url = "http://localhost:3000/discussions/" + next;
    $.getJSON(url, function(data){
      var newDiscussion = new DiscussionData(data["id"], data["title"], data["content"],
                              data["user"], data["comments"]);
      console.log(newDiscussion)
      $(".title").html(newDiscussion.title);
      $(".content").html(newDiscussion.content);
      $(".author").html("Posted by " + newDiscussion.author() + ".");
      $(".discussion-show").data("id", newDiscussion.id);
      $(".edit").attr("href", newDiscussion.id + "/edit");
      $(".delete").attr("href", newDiscussion.id);

      var len = newDiscussion.comments.length;
      var html = '';
      for(var i = 0; i < len; i++){
        html += '<div class="panel panel-default">'
        html += '     <div class="panel-body">'
        html += '   <p class="comment-content">' + newDiscussion.comments[i].content +'</p>'
        html += '   <p class="comment-posted-by">Posted by ' + newDiscussion.comments[i].user["name"] + '.</p>'
        html += ' </div></div> '
      }
      $(".comments").html(html);
      console.log(html);
    });
  });
});

function DiscussionData(id, title, content, user, comments){
  this.id = id;
  this.title = title;
  this.content = content;
  this.user = user;
  this.comments = comments;
  this.author = function(){
    return user["name"];
  }
}

</script>